# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|

  config.vm.box = "ol76"

  config.vm.provider "virtualbox" do |vb|
    # Display the VirtualBox GUI when booting the machine
    vb.gui = false
      # Customize the amount of memory on the VM:
    vb.memory = "1024"
  end

  config.vm.provision "shell" do |m|
    m.inline = "mv /vagrant/motd /tmp/motd"
  end
  
  config.vm.provision "shell" do |b|
    b.path = "base.sh"
  end

end
